name: Build AriaNg Docker Image

on:
  workflow_dispatch:      # 手动触发（可选）
  push:
    branches: [ main ]
  schedule:
    # 每天北京时间 8:00 自动拉取上游更新
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AriaNg source
        uses: actions/checkout@v4
        with:
          repository: mayswind/AriaNg   # 直接拉上游
          ref: master                   # 上游分支
          path: dist                     # 放在 ./src

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build static files
        run: |
          cd dist
          npm ci
          npm run build
          # 默认产物在 src/dist 目录

      - name: Set up QEMU & Buildx
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .          # Dockerfile 在根目录
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ariang:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ariang:${{ github.sha }}
